services:
  bot:
    build:
      context: ./bot
    container_name: rag-bot
    env_file:
      - ./bot/.env

  backend:
    build:
      context: ./backend
    container_name: rag-backend
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_HOST: "rag-pgvector"
    ports:
      - "7007:7007"
    depends_on:
      - db

  db:
    image: pgvector/pgvector:0.8.1-pg17-trixie
    container_name: rag-pgvector
    restart: unless-stopped
    #ports:
    #  - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data 
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - ./backend/.env
