services:
  db:
    image: pgvector/pgvector:0.8.1-pg17-trixie
    container_name: rag-pgvector
    restart: unless-stopped
    #user: 1024:1024
    environment:
      POSTGRES_DB: RAG_DB
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data 
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: "./.env"
