name: Build Docker Images (test)
on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile
          push: false
          tags: test/rag-backend:latest

      - name: Build and push Bot Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./bot
          file: ./bot/Dockerfile
          push: false
          tags: test/rag-bot:latest